#cloud:
#  aws:
#    credentials:
#      accessKey: AKIAR6BPEVVAGMHQVG4B
#      secretKey: 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
#    s3:
#      bucket:
#        url: https://s3.ap-northeast-2.amazonaws.com/springboot-db
#        nodeValue: springboot-db
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: 'false'

cloud:
  aws:
    credentials:
      access-key: {AKIAR6BPEVVAGMHQVG4B}
      secret-key: {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}
    s3:
      bucket: springboot-db
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: beomsoo
    url: jdbc:h2:mem:cafereview
    password: sparta9